In [2]:
import numpy as np

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10, 4)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [11]:
py_list = [1,2,3,4,5]

np_array = np.array(py_list)
print(np_array)
print(np_array[3])

np_array[2] = 7
np_array

[1 2 3 4 5]
4


array([1, 2, 7, 4, 5])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(3, 9)

array([3, 4, 5, 6, 7, 8])

In [15]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimensional Arrays


In [16]:
# rows, cols
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [20]:
n[0][2]

np.int64(3)

In [21]:
n[2]

array([7, 8, 9])

In [22]:
n[2] = [1,2]

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [23]:
n[2] = [-7,-8,-9]

In [24]:
n

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [-7, -8, -9]])

In [25]:
n[:,1]

array([ 2,  5, -8])

In [26]:
n[:,1] = [5,90,1]

n

array([[ 1,  5,  3],
       [ 4, 90,  6],
       [-7,  1, -9]])

## Random Generated Arrays

In [38]:
np.random.seed(10) # TO generate the "same" random numbers
np.random.rand(5,2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [39]:
np.random.randn(3,3)

array([[ 0.26551159,  0.10854853,  0.00429143],
       [-0.17460021,  0.43302619,  1.20303737],
       [-0.96506567,  1.02827408,  0.22863013]])

In [40]:
100 * np.random.rand(3,3)

array([[54.2544368 , 14.21700476, 37.33407601],
       [67.41336151, 44.18331744, 43.40139933],
       [61.77669785, 51.31382426, 65.03971819]])

In [41]:
np.random.randint(low=0, high=100, size=(3,3))

array([[77, 22, 23],
       [94, 11, 28],
       [74, 88,  9]])

## Element-wise Operation

In [43]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [46]:
a + 1

array([0, 2, 4, 6, 8])

In [47]:
a * 2

array([0, 2, 4, 6, 8])

In [48]:
b = [2,45,3,1,45]

b * a

array([  0,  45,   6,   3, 180])

## Comparison Operations

In [49]:
a

array([0, 1, 2, 3, 4])

In [50]:
a >= 2

array([False, False,  True,  True,  True])

In [51]:
a == 3

array([False, False, False,  True, False])

In [52]:
a > b

array([False, False, False,  True, False])

In [57]:
a[[True, True, False, True, False]]

array([0, 1, 3])

In [53]:
# Return the elements of a that are greater than the corresponding elements in b.
a[a > b]

array([3])

## Summarizing Operations

In [58]:
a.min()

np.int64(0)

In [59]:
a.max()

np.int64(4)

In [60]:
a.sum()

np.int64(10)

In [61]:
a.mean()

np.float64(2.0)

In [62]:
a.std()

np.float64(1.4142135623730951)

In [63]:
n

array([[ 1,  5,  3],
       [ 4, 90,  6],
       [-7,  1, -9]])

In [64]:
n.sum()

np.int64(94)