# **2025 Homework - Introduction**

## Question 1. Pandas Version
version 2.3.1

In [3]:
import pandas as pd
import numpy as np

In [4]:
print(f"Pandas: {pd.__version__}\nNumpy: {np.__version__}")

Pandas: 2.3.1
Numpy: 2.3.1


In [5]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

## Question 2. Records Count
9704 Records

In [6]:
df.shape[0]

9704

## Question 3. Fuel Types
2 fuel types, gasoline and diesel

In [7]:
df["fuel_type"].nunique()

2

In [8]:
df["fuel_type"].unique()

array(['Gasoline', 'Diesel'], dtype=object)

## Question 4. Missing Values
4 columns with missing values: num_cylinders, horsepower, acceleration, num_doors

In [9]:
df.columns[df.isnull().sum() > 0]

Index(['num_cylinders', 'horsepower', 'acceleration', 'num_doors'], dtype='object')

## Question 5. Max Fuel Efficiency
Max Fuel efficiency is 23.75

In [10]:
cars_asia = df[df["origin"].str.lower() == "asia"]
cars_asia

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [11]:
cars_asia["fuel_efficiency_mpg"].max(), df["fuel_efficiency_mpg"].max()

(np.float64(23.759122836520497), np.float64(25.96722204888372))

## Question 6. Median Value of Horsepower
The median HP went from 149 originally, to 152 after the null values were replaced with the mode HP.

In [13]:
median_horsepower = df["horsepower"].median()
median_horsepower

np.float64(149.0)

In [33]:
mode_horsepower = df["horsepower"].mode()[0]
mode_horsepower

np.float64(152.0)

In [36]:
# Alternative way of counting values in a column
df["horsepower"].value_counts()

horsepower
152.0    142
145.0    141
151.0    134
148.0    130
141.0    130
        ... 
40.0       1
57.0       1
245.0      1
252.0      1
61.0       1
Name: count, Length: 192, dtype: int64

In [39]:
horsepowers = df["horsepower"].copy()
horsepowers

0       159.0
1        97.0
2        78.0
3         NaN
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [49]:
horsepowers.fillna(mode_horsepower).median()

np.float64(152.0)

## Question 7. Sum of Weights

In [55]:
cars_asia = cars_asia[["vehicle_weight", "model_year"]]
cars_asia.head()

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016

In [62]:
car_values = cars_asia.iloc[[i for i in range(7)]]
car_values

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [68]:
X = car_values.values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [71]:
XTX = X.T.dot(X)

X.T.dot(X)

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [72]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [66]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [74]:
w = XTX_inv.dot(X.T).dot(y)

In [75]:
w.sum()

np.float64(0.5187709081074016)